version: '3'
services:
    node:
        image: 'node:16-alpine'
        working_dir: /var/www/html
        ports:
            - '${APP_PORT:-3000}:3000'
        volumes:
            - '.:/var/www/html'
        tty: true
